//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSDebugCoreLib.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HexEditor {
            get {
                return ((string)(this["HexEditor"]));
            }
            set {
                this["HexEditor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TextEditor {
            get {
                return ((string)(this["TextEditor"]));
            }
            set {
                this["TextEditor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImgEditor {
            get {
                return ((string)(this["ImgEditor"]));
            }
            set {
                this["ImgEditor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WorkingDirectory {
            get {
                return ((string)(this["WorkingDirectory"]));
            }
            set {
                this["WorkingDirectory"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DiffTool {
            get {
                return ((string)(this["DiffTool"]));
            }
            set {
                this["DiffTool"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
                    <CExtensionsMap xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
                        <Values>
                            <CExtensionMapElement>
                                <Extension>.bin</Extension>
                                <Tool>Hex Editor</Tool>
                            </CExtensionMapElement>
                            <CExtensionMapElement>
                                <Extension>.hex</Extension>
                                <Tool>Hex Editor</Tool>
                            </CExtensionMapElement>
                            <CExtensionMapElement>
                                <Extension>.dmp</Extension>
                                <Tool>Hex Editor</Tool>
                            </CExtensionMapElement>
                            <CExtensionMapElement>
                                <Extension>.txt</Extension>
                                <Tool>Text Editor</Tool>
                            </CExtensionMapElement>
                            <CExtensionMapElement>
                                <Extension>.raw</Extension>
                                <Tool>Image Editor</Tool>
                            </CExtensionMapElement>
                        </Values>
                    </CExtensionsMap>
                ")]
        public global::VSDebugCoreLib.CExtensionsMap ExtensionsMap {
            get {
                return ((global::VSDebugCoreLib.CExtensionsMap)(this["ExtensionsMap"]));
            }
            set {
                this["ExtensionsMap"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\n                    <CAliasMap xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-insta" +
            "nce\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\n                        <Valu" +
            "es />\n                    </CAliasMap>\n                ")]
        public global::VSDebugCoreLib.CAliasMap AliasMap {
            get {
                return ((global::VSDebugCoreLib.CAliasMap)(this["AliasMap"]));
            }
            set {
                this["AliasMap"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\n                    <CCmdHistory xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-ins" +
            "tance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\n                        <Va" +
            "lues />\n                    </CCmdHistory>\n                ")]
        public global::VSDebugCoreLib.CCmdHistory CmdHistory {
            get {
                return ((global::VSDebugCoreLib.CCmdHistory)(this["CmdHistory"]));
            }
            set {
                this["CmdHistory"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Version {
            get {
                return ((int)(this["Version"]));
            }
            set {
                this["Version"] = value;
            }
        }
    }
}
